### ISSUE TITLE
Publish role on Ansible Galaxy

### ISSUE THREAD

**Issue by stdevel** [oasis-roles/ansible-role-redhat_satellite6_storage#2]
It would be handy to have this role published on Ansible Galaxy.

See also PR #1

**Comment by itewk** [comment]
@stdevel step (i have lost count) is now complete. This has been moved to oasis-roles. The next step is that oasis is moving to collections (like everyone), so they need to make a satellite collection and then include this in there.

**Comment by itewk** [comment]
@greg-hellings fyi.

**Comment by greg-hellings** [comment]
I just forced a commit on the README.md file to update its connection to the Travis badge. That will initiate a Travis build and will trigger an import to the oasis_roles namespace directly on Galaxy.

Creating a collection will be dependent on https://github.com/ansible-community/molecule/pull/2609 getting merged. Until then, you can reference this like a normal role.

**Comment by itewk** [comment]
sweet. looks like it got published. https://galaxy.ansible.com/oasis_roles/ansible-role-redhat_satellite6_storage

Shoudl we update the name of this repo to meet whatever standard you all use? we had `ansible-role-` on it because of where it lived before. Or just leave it as is and renmae when it can be put in collection.

**Comment by greg-hellings** [comment]
Renaming the repository after import isn't going to rename the role in Galaxy. For that you would need to explicitly set the name in meta/main.yml. You're welcome to do that, or we can wait until it's imported to a collection and do the rename as part of that. The two aren't mutually exclusive, either.

**Comment by itewk** [comment]
i think we can close this issue and I have opened https://github.com/oasis-roles/ansible-role-redhat_satellite6_storage/issues/3 to figure out if role should be renamed and to what.

I don't seem to have permissions to close this so will need you or someone else to do so @greg-hellings

**Comment by stdevel** [comment]
Great, thanks a lot for the work, @itewk @greg-hellings!
The last thing we could have a look at is why the CI pipeline isn't working. Looks like there is an error in the configuration.

**Comment by greg-hellings** [comment]
@itewk - You should have access to close this issue now. Go ahead and give it a shot.

As for the CI failures, I'll leave that for those who wrote the role!

**Comment by stdevel** [comment]
Thanks for the feedback, @greg-hellings - I will create another issue and have a look at it. :)
